name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Application Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests and Build with Gradle
      run: |
        ./gradlew testGithubReleaseUnitTest