name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  GITHUB_APK_PATH: app/build/outputs/apk/github/release
  GITHUB_BUNDLE_PATH: app/build/outputs/bundle/githubRelease

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Save release version
      run: |
        VERSION=${{ github.ref_name }}
        echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Checkout keystore repo
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: app/keystore

    - name: Prepare signing properties
      run: |
        mkdir signing && touch signing/release.properties
        echo "storeFile=${{ secrets.KEYSTORE_FILE }}" >> signing/release.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing/release.properties
        echo "keyAlias=${{ secrets.RELEASE_SIGN_KEY_ALIAS }}" >> signing/release.properties
        echo "keyPassword=${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}" >> signing/release.properties
        
        touch signing/legacy.properties
        echo "storeFile=${{ secrets.KEYSTORE_FILE }}" >> signing/legacy.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing/legacy.properties
        echo "keyAlias=${{ secrets.RELEASE_SIGN_KEY_ALIAS }}" >> signing/legacy.properties
        echo "keyPassword=${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}" >> signing/legacy.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests and Build with Gradle
      run: |
        ./gradlew assembleGithubRelease --stacktrace
        ./gradlew bundleGithubRelease

    - name: Upload Github Release APK
      uses: actions/upload-artifact@v4
      with:
        name: Github Release APK
        path: ${{ env.GITHUB_APK_PATH }}/*

    - name: Upload Github Bundle
      uses: actions/upload-artifact@v4
      with:
        name: github-release.aab
        path: ${{ env.GITHUB_BUNDLE_PATH }}/app-github-release.aab

    - name: Upload files to GH release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ${{ env.GITHUB_APK_PATH }}/app-github-release.apk
        asset_name: aerial-views-${{ env.VERSION }}.apk